.github/workflows/build.yml
sonar-project.properties

Commit de desarrollo, test estático de código

feat: Añadido soporte para Sonarqube

---

backend/diary_entries/serializer.py
backend/diary_entries/views.py

Se ha hecho opcional el relleno de los campos negative_thoughts, positive_thoughts y body_parts, ya que consideramos que una persona podría pasar un día sin tener pensamientos positivos/negativos y puede no dolerle nada un día.

feat: swagger preparado para diarios

---

frontend/src/app/app-routing.module.ts
frontend/src/app/pages/analiticas/analiticas.page.html
frontend/src/app/pages/new-analytic/new-analytic.page.html
frontend/src/app/pagina-inicial/pagina-inicial-routing.module.ts
frontend/src/app/pagina-inicial/pagina-inicial.module.ts
frontend/src/app/pagina-inicial/pagina-inicial.page.html
frontend/src/app/pagina-inicial/pagina-inicial.page.spec.ts
frontend/src/app/pagina-inicial/pagina-inicial.page.ts

Pequeño pantallazo que informa al usuario que está utilizando una aplicación en desarrollo

feat: Pantallazo Inicial

---

backend/users/urls.py
backend/users/views.py

Se ha realizado el cierre de sesion, revokando el token

FEAT: Logout completado

---

backend/metrics/urls.py
backend/metrics/views.py

Busqueda de measures por id de paciente y metrica

FEAT: Busqueda de measures

---

backend/deploy_settings.py

Añadido settings.py específico de despliegue y añadidas carpetas de migraciones vacías

feat: Configuración inicial para despliegue automático

---

frontend/src/app/pages/new-analytic/new-analytic.page.html
frontend/src/app/pages/new-analytic/new-analytic.page.ts
frontend/src/app/pages/nueva-entrada-fisica/nueva-entrada-fisica.page.html
frontend/src/app/pages/nueva-entrada-fisica/nueva-entrada-fisica.page.ts
frontend/src/app/pages/nueva-entrada-mental/nueva-entrada-mental.page.html
frontend/src/app/pages/nueva-entrada-mental/nueva-entrada-mental.page.ts
frontend/src/app/services/new-analytic.service.ts
frontend/src/app/services/nueva-entrada-fisica.service.ts
frontend/src/app/services/nueva-entrada-mental.service.ts

Reverts JStockwell/ISPP-G9-22-23#109

Revert "Temp llamadas apis sergio"

---

frontend/src/app/pages/new-analytic/new-analytic.page.html
frontend/src/app/pages/nueva-entrada-fisica/nueva-entrada-fisica.page.html
frontend/src/app/tab2/tab2.page.html
frontend/src/app/tab2/tab2.page.ts

Se han creado funciones para que se muestren los emoticonos en el diario emocional

Fix diario emocional

---

backend/diary_entries/models.py
backend/diary_entries/serializer.py
backend/diary_entries/views.py

Se ha añadido el campo done_exercise a las entradas de diario fisico

FEAT: Campo ejercicio

---

backend/diary_entries/views.py
backend/metrics/views.py

Ahora se devuelve el id de metric y measure al hacer post

FEAT: Id al hacer post

---

backend/metrics/urls.py
backend/metrics/views.py

Se ha implementado un get por id de paciente de metricinfo no usados

FEAT: Método para ver que info no tiene un usuario

---

backend/diary_entries/models.py
backend/diary_entries/serializer.py
backend/diary_entries/views.py

Campos opcionales en entradas de diario

FEAT: Campos opcionales

---

backend/users/urls.py
backend/users/views.py

Asignación desasignación y listado de pacientes sobre médicos

FEAT: Asignación, desasignación y listado

---

frontend/src/app/pages/añadir-detalles-analiticas/añadir-detalles-analiticas.page.html
frontend/src/app/pages/detalles-mental/detalles-mental.page.html
frontend/src/app/pages/modificar-detalles/modificar-detalles.page.html
frontend/src/app/pages/modificar-fisico/modificar-fisico.page.html
frontend/src/app/pages/modificar-fisico/modificar-fisico.page.ts
frontend/src/app/pages/modificar-mental/modificar-mental.page.html
frontend/src/app/pages/modificar-mental/modificar-mental.page.ts
frontend/src/app/pages/new-analytic/new-analytic.page.html
frontend/src/app/pages/new-analytic/new-analytic.page.scss
frontend/src/app/pages/nueva-cita/nueva-cita.page.html
frontend/src/app/pages/nueva-entrada-mental/nueva-entrada-mental.page.html
frontend/src/app/pages/users/users.page.html
frontend/src/app/pagina-inicial/pagina-inicial.page.html
frontend/src/app/tab2/tab2.page.html
frontend/src/app/tabs/tabs.page.html

Textos en inglés encontrados a español, faltas de ortografías y puntuación, y placeholders corregidos.

fix(frontend): Aplicado feedback sobre el texto de la aplicación

---

frontend/src/app/pages/detalles-mental/detalles-mental.page.ts

Corrección de fallo que ha parecido tras haber estado probando

F53 feedback mental

---

frontend/src/app/app-routing.module.ts
frontend/src/app/pages/detalles-fisico/detalles-fisico.page.html
frontend/src/app/pages/detalles-fisico/detalles-fisico.page.ts
frontend/src/app/pages/detalles-mental/detalles-mental.page.html
frontend/src/app/pages/detalles-mental/detalles-mental.page.ts
frontend/src/app/pages/modificar-fisico/modificar-fisico.page.html
frontend/src/app/pages/modificar-fisico/modificar-fisico.page.ts
frontend/src/app/pages/modificar-mental/modificar-mental.page.html
frontend/src/app/pages/modificar-mental/modificar-mental.page.ts
frontend/src/app/pages/nueva-entrada-mental/nueva-entrada-mental.page.html
frontend/src/app/pages/nueva-entrada-mental/nueva-entrada-mental.page.ts
frontend/src/app/tab2/tab2.page.ts
frontend/src/app/tabs/tabs-routing.module.ts
frontend/src/app/tabs/tabs.page.html

Corrección de las urls de la sección mental que hacia que cuando se fuera a crear una nueva entrada, el logo del tab no se colorease, además se ha corregido la animación de volver hacia atrás de la sección mental y física.

FIX urls seccion mental y boton retroceder

---

frontend/src/app/pages/analiticas/analiticas.page.html
frontend/src/app/pages/analiticas/analiticas.page.scss
frontend/src/app/pages/analiticas/analiticas.page.ts
frontend/src/app/pages/calendario/calendario.page.html
frontend/src/app/pages/users/users.page.ts
frontend/src/app/services/analiticas.service.ts

También se ha puesto la plantilla para que aparezca cuando el usuario no tiene análiticas. Y modificada la apariencia de unos pocos botones.

fix(frontend): Arreglado el inicio de sesión tras registro

---

frontend/src/app/app-routing.module.ts
frontend/src/app/pages/medic-home/medic-home-routing.module.ts
frontend/src/app/pages/medic-home/medic-home.module.ts
frontend/src/app/pages/medic-home/medic-home.page.html
frontend/src/app/pages/medic-home/medic-home.page.spec.ts
frontend/src/app/pages/medic-home/medic-home.page.ts
frontend/src/app/pages/medics/medics-routing.module.ts
frontend/src/app/pages/medics/medics.module.ts
frontend/src/app/pages/medics/medics.page.html
frontend/src/app/pages/medics/medics.page.scss
frontend/src/app/pages/medics/medics.page.spec.ts
frontend/src/app/pages/medics/medics.page.ts
frontend/src/app/pagina-inicial/pagina-inicial.page.html
frontend/src/app/services/medics.service.spec.ts
frontend/src/app/services/medics.service.ts
frontend/src/app/services/pagina-inicial.service.spec.ts
frontend/src/app/services/pagina-inicial.service.ts

Hay una pequeña cosa por terminar de pulir pero es para que podáis ir trabajando

F34 registro de médicos

---

frontend/src/app/pages/login/login.page.ts
frontend/src/app/pagina-inicial/pagina-inicial.page.ts
frontend/src/app/services/pagina-inicial.service.ts

Se ha implementado una funcionalidad que lo que hace es redirigir a los usuarios dependiendo de con que tipo de cuenta han iniciado sesión.

Correción para que dirija de forma automática

---

frontend/src/app/app-routing.module.ts
frontend/src/app/pages/modificar-mental/modificar-mental.page.ts

Se ha arreglado la pantalla en negro que parecía al tras modificar una entrada mental

Arreglo de pantalla negra modificar mental

---

frontend/src/app/app-routing.module.ts
frontend/src/app/pages/preferencias-de-usuario/preferencias-de-usuario-routing.module.ts
frontend/src/app/pages/preferencias-de-usuario/preferencias-de-usuario.module.ts
frontend/src/app/pages/preferencias-de-usuario/preferencias-de-usuario.page.html
frontend/src/app/pages/preferencias-de-usuario/preferencias-de-usuario.page.spec.ts
frontend/src/app/pages/preferencias-de-usuario/preferencias-de-usuario.page.ts
frontend/src/app/services/users.service.ts

Se ha creado la vista con el formulario de preferencia para compartir de los usuarios, esta a falta de unirlo con Tabs y con la vista de usuario

F58 preferencias de usuario

---

frontend/src/app/pages/medic-home/medic-home.page.html
frontend/src/app/pages/nuevo-paciente-medico/nuevo-paciente-medico.page.html

F36 lista pacientes

---

backend/users/urls.py
backend/users/views.py

Revert "FEAT: Cambios de seguridad en users"

---

frontend/src/app/pages/calendario/calendario.page.html
frontend/src/app/pages/modificar-cita/modificar-cita.page.html
frontend/src/app/pages/nueva-cita/nueva-cita.page.html

He corregido algunos fallos de color en los botones de retroceder de la aplicación.

Correción de errores en el calendario

---

frontend/src/app/app-routing.module.ts
frontend/src/app/pages/tyc/tyc-routing.module.ts
frontend/src/app/pages/tyc/tyc.module.ts
frontend/src/app/pages/tyc/tyc.page.html
frontend/src/app/pages/tyc/tyc.page.ts
frontend/src/app/pagina-inicial/pagina-inicial.page.html

Añadidos los tyc a la pagina de inicio

feat: Terminos y condiciones

---

frontend/src/app/app.component.html
frontend/src/app/app.component.ts
frontend/src/app/services/users.service.ts
frontend/src/app/tabs/tabs.page.html
frontend/src/app/tabs/tabs.page.ts

Al final he hecho que no salgan en las pantallas de registro y log in, y que salgan para tanto médicos como pacientes

Fix: Anuncios Médico

---

frontend/src/app/pages/preferencias-de-usuario/preferencias-de-usuario.page.html

Se ha corregido un botón que no estaba

Correcion rapida

---

frontend/src/app/pages/medico-diario-fisico-detalles/medico-diario-fisico-detalles.page.ts

Correccion esquizofrenia

---

frontend/src/app/pages/patient/patient.page.html

no se trajo el cambio de la url del botón a develop, cambio menor para forzar una actualización en develop del código

fix: url medico analíticas

---

backend/scripts/dummyUsers.py
backend/scripts/populateDB.py

4 pacientes, 3 de ellos asociados a un médico, con distintos grados de mostrado de datos

feat(backend): Script con usuarios por defecto
